import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createCognitiveIndividual } from '../src/cognitive-individual.mjs';
import { runCognitiveLoop } from '../src/cognitive-loop.mjs';
import { promoteVerifiedCognitiveLearning } from '../src/cognitive-learning-bridge.mjs';
const now='2026-09-15T09:00:00.000Z';
const member=(id,tags)=>createCognitiveIndividual({individualId:id,parentAgentId:'mahoraga-core',displayName:id,archetype:`${id}-mind`,perspective:`${id} perspective`,communicationStyle:'evidence-first',traits:{curiosity:0.7},epistemicPosture:{evidenceThreshold:0.8,uncertaintyTolerance:0.4,dissentDisposition:'surface-material-dissent'},perspectiveTags:tags,privateEpisodicRefs:[]},{observedAt:now});
const members=[member('builder-agent',['engineering']),member('skeptic-agent',['risk']),member('research-agent',['evidence'])];
const base={members,requiredPerspectiveTags:['engineering','risk','evidence'],positions:[{individualId:'builder-agent',conclusion:'repair',confidence:0.9,evidenceRefs:['ev:a'],assumptions:[],unknowns:[],dissentTags:[]},{individualId:'research-agent',conclusion:'repair',confidence:0.88,evidenceRefs:['ev:b'],assumptions:[],unknowns:[],dissentTags:[]},{individualId:'skeptic-agent',conclusion:'repair',confidence:0.85,evidenceRefs:['ev:c'],assumptions:[],unknowns:[],dissentTags:[]}],metacognition:{evidenceCoverage:0.95,calibratedConfidence:0.9,knownUnknowns:[],materialConflictCount:0,reversible:true},observedState:{queueDepth:3},stateUncertainty:0.1,proposedAction:{actionId:'repair-capacity',effects:{queueDepth:-1},uncertainty:0.1},plannerSnapshot:{workers:[],activeLeases:[],repository:{verified:true},taskCounts:{},objectives:[],providers:[]}};
test('verified admitted cognition becomes institutional learning without private memory or authority',()=>{const cycle=runCognitiveLoop(base);const out=promoteVerifiedCognitiveLearning({cycle,verification:{verified:true,sourceFingerprint:cycle.fingerprint,evidenceRefs:['verify:receipt']},observedAt:now});assert.equal(out.promotable,true);assert.equal(out.record.provenance,'verified-outcome');assert.deepEqual(out.record.evidenceRefs,['ev:a','ev:b','ev:c','verify:receipt']);assert.equal(JSON.stringify(out).includes('privateEpisodicRefs'),false);assert.equal(JSON.stringify(out).includes('ownerAuthority'),false);});
test('hold or dissent escalation cannot promote even with a verified receipt',()=>{const cycle=runCognitiveLoop({...base,stateUncertainty:0.65});const out=promoteVerifiedCognitiveLearning({cycle,verification:{verified:true,sourceFingerprint:cycle.fingerprint,evidenceRefs:['verify:receipt']},observedAt:now});assert.equal(out.promotable,false);assert.equal(out.reason,'cycle-not-promotable');assert.equal(out.record,null);});
test('verification must bind the exact immutable cognitive receipt',()=>{const cycle=runCognitiveLoop(base);assert.throws(()=>promoteVerifiedCognitiveLearning({cycle,verification:{verified:true,sourceFingerprint:'0'.repeat(64),evidenceRefs:['verify:receipt']},observedAt:now}),{code:'cognitive-learning-verification-mismatch'});});
test('unverified cognition fails closed instead of manufacturing institutional memory',()=>{const cycle=runCognitiveLoop(base);const out=promoteVerifiedCognitiveLearning({cycle,verification:{verified:false,sourceFingerprint:cycle.fingerprint,evidenceRefs:[]},observedAt:now});assert.equal(out.promotable,false);assert.equal(out.reason,'verification-required');assert.equal(out.record,null);});

import { executeCognitiveCapability } from '../src/cognitive-worker.mjs';
test('cognitive.learn is an executable bounded capability',async()=>{const cycle=runCognitiveLoop(base);const result=await executeCognitiveCapability('cognitive.learn',{capabilityInput:{learningInput:{cycle,verification:{verified:true,sourceFingerprint:cycle.fingerprint,evidenceRefs:['verify:receipt']},observedAt:now}}});assert.equal(result.verified,true);assert.equal(result.learning.promotable,true);assert.equal(result.receiptMetadata.routeWorker,'cognitive-core');});

test('manifest routes cognitive.learn through the existing cognitive core only',()=>{const manifest=JSON.parse(readFileSync(new URL('../mahoraga.manifest.json',import.meta.url),'utf8'));const workers=manifest.workers.filter(w=>w.capabilities.includes('cognitive.learn'));assert.equal(workers.length,1);assert.equal(workers[0].id,'cognitive-core');assert.equal(workers[0].costClass,'deterministic');assert.equal(workers[0].routing.requiresAttendedDesktop,false);});
