import type { AgentId, CommandPlane, GithubSnapshot, IntentKind, WriteVerb } from "./types";

export type ArsenalCommand = {
  id: string;
  label: string;
  command: string;
  owner: AgentId;
  plane: CommandPlane;
  group: string;
  hint: string;
  keywords: string;
  intent: IntentKind;
  workflowFile?: string;
  cliHint?: string;
  issueNumber?: number;
  targetUrl?: string;
  writeVerb?: WriteVerb;
};

export const ARSENAL: ArsenalCommand[] = [
  {
    id: "inspect-repo",
    label: "Inspect live repository",
    command: "Inspect the live Mahoraga repository: health, open issues, and current head.",
    owner: "repository",
    plane: "live",
    group: "Live on this deck",
    hint: "Public GitHub head, issues, README. No token.",
    keywords: "inspect repo repository mahoraga head sha",
    intent: "repository-inspect",
  },
  {
    id: "health-scan",
    label: "Live health scan",
    command: "Verify Mahoraga system health against the live GitHub repository and current head SHA.",
    owner: "repository",
    plane: "live",
    group: "Live on this deck",
    hint: "Zero-token health vs public main.",
    keywords: "health status gap verify system",
    intent: "health-scan",
  },
  {
    id: "isolate-issues",
    label: "Isolate open issues",
    command: "List open GitHub issues and allocate each to an isolated specialist cell.",
    owner: "admin",
    plane: "live",
    group: "Live on this deck",
    hint: "One issue, one owner, one fence.",
    keywords: "isolate issues allocate assign backlog",
    intent: "issue-isolate",
  },
  {
    id: "inspect-78",
    label: "Issue #78 — protect main",
    command: "Inspect GitHub issue #78 and isolate it to its owner cell.",
    owner: "admin",
    plane: "live",
    group: "Live on this deck",
    hint: "Settings write is now a live ruleset. Use Inspect main protection to prove it.",
    keywords: "78 protect main branch ruleset",
    intent: "issue-inspect",
    issueNumber: 78,
  },
  {
    id: "inspect-85",
    label: "Issue #85 — Destiny trust",
    command: "Inspect GitHub issue #85 and isolate it to its owner cell.",
    owner: "relay",
    plane: "live",
    group: "Live on this deck",
    hint: "receiptTrust.mode is unconfigured. No Destiny fire from here.",
    keywords: "85 destiny trust receipt",
    intent: "issue-inspect",
    issueNumber: 85,
  },
  {
    id: "inspect-87",
    label: "Issue #87 — adaptive starters",
    command: "Inspect GitHub issue #87 and isolate it to its owner cell.",
    owner: "coordinator",
    plane: "live",
    group: "Live on this deck",
    hint: "Composer-only starters on the Vercel workspace.",
    keywords: "87 starters workspace ui",
    intent: "issue-inspect",
    issueNumber: 87,
  },
  {
    id: "inspect-51",
    label: "Issue #51 — self-update",
    command: "Inspect GitHub issue #51 and isolate it to its owner cell.",
    owner: "repair",
    plane: "live",
    group: "Live on this deck",
    hint: "Self-update is verify-then-activate. 7.0 is not live Windows.",
    keywords: "51 self-update yourself",
    intent: "issue-inspect",
    issueNumber: 51,
  },
  {
    id: "inspect-83",
    label: "Issue #83 — branch cleanup",
    command: "Inspect GitHub issue #83 and isolate it to its owner cell.",
    owner: "admin",
    plane: "live",
    group: "Live on this deck",
    hint: "Contained-branch ledger. Preview deletes before any delete.",
    keywords: "83 cleanup branches contained",
    intent: "issue-inspect",
    issueNumber: 83,
  },
  {
    id: "inspect-97",
    label: "Issue/PR #97 — cycle candidate",
    command: "Inspect GitHub issue #97 and isolate it to its owner cell.",
    owner: "repair",
    plane: "live",
    group: "Live on this deck",
    hint: "Producer-smoke candidate from the four-hour cycle.",
    keywords: "97 sovereign candidate scan report",
    intent: "issue-inspect",
    issueNumber: 97,
  },
  {
    id: "inspect-98",
    label: "Issue/PR #98 — integration gap",
    command: "Inspect GitHub issue #98 and isolate it to its owner cell.",
    owner: "admin",
    plane: "live",
    group: "Live on this deck",
    hint: "Verify currently fails. Do not treat as merged.",
    keywords: "98 integration dispatch gap sovereign",
    intent: "issue-inspect",
    issueNumber: 98,
  },
  {
    id: "inspect-99",
    label: "Issue/PR #99 — cycle candidate",
    command: "Inspect GitHub issue #99 and isolate it to its owner cell.",
    owner: "repair",
    plane: "live",
    group: "Live on this deck",
    hint: "Second producer-smoke scan report. Same rules as #97.",
    keywords: "99 sovereign candidate scan report",
    intent: "issue-inspect",
    issueNumber: 99,
  },
  {
    id: "version-ledger",
    label: "Show version ledger",
    command: "Show the version ledger: live 3.6.0, candidate 7.0.0-alpha.1, and this operator deck.",
    owner: "repository",
    plane: "live",
    group: "Live on this deck",
    hint: "One console. TypeScript lock. Vercel host. Windows 7.0 stays off.",
    keywords: "version ledger 3.6.0 7.0.0-alpha operator deck typescript vercel",
    intent: "version-inspect",
  },
  {
    id: "github-admin",
    label: "GitHub admin read",
    command: "GitHub admin read: issues, pull requests, labels, and default branch. Do not protect main from here.",
    owner: "admin",
    plane: "live",
    group: "Live on this deck",
    hint: "Public metadata plus write-status when gh is present.",
    keywords: "admin github issues pulls labels branch",
    intent: "github-admin",
  },
  {
    id: "scout-repo",
    label: "Scout public repo",
    command: "Fetch https://github.com/michaeljwilliams0123/mahoraga and extract the current public summary.",
    owner: "scout",
    plane: "live",
    group: "Live on this deck",
    hint: "Allowlisted HTTPS GET.",
    keywords: "scout fetch browse github mahoraga",
    intent: "web-scout",
    targetUrl: "https://github.com/michaeljwilliams0123/mahoraga",
  },
  {
    id: "scout-docs",
    label: "Scout GitHub docs",
    command: "Fetch https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows and extract the schedule event summary.",
    owner: "scout",
    plane: "live",
    group: "Live on this deck",
    hint: "Allowlisted docs.github.com read.",
    keywords: "scout docs actions cron schedule",
    intent: "web-scout",
    targetUrl: "https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows",
  },
  {
    id: "posture",
    label: "Audit connection posture",
    command: "Audit outbound-only connection posture. Deny inbound tunnels. Report relay and GitHub surfaces.",
    owner: "assurance",
    plane: "live",
    group: "Live on this deck",
    hint: "Fail-closed. No device reachability from this console.",
    keywords: "posture audit connection relay outbound inbound tunnel",
    intent: "posture-audit",
  },
  {
    id: "repair",
    label: "Repair isolate",
    command: "Repair isolate the current incident without spending model credits or opening a supervisor shell.",
    owner: "repair",
    plane: "live",
    group: "Live on this deck",
    hint: "Quarantine a cell. No paid retry.",
    keywords: "repair fix incident quarantine",
    intent: "repair-isolate",
  },
  {
    id: "arsenal-list",
    label: "List the full arsenal",
    command: "List the command arsenal and show what this deck can run live versus GitHub, loopback, or deny.",
    owner: "coordinator",
    plane: "live",
    group: "Live on this deck",
    hint: "Coverage receipt. Every command is listed.",
    keywords: "arsenal commands help what can you do palette",
    intent: "arsenal-list",
  },
  {
    id: "cycle-inspect",
    label: "Review 4hr sovereign cycle",
    command: "Inspect the four-hour sovereign candidate cycle, last GitHub run, and whether Mahoraga actually self-updated.",
    owner: "repair",
    plane: "github",
    group: "GitHub ledger",
    hint: "Live Actions pulse. Dispatch is a separate write command.",
    keywords: "four hour 4hr sovereign cycle self-update self-heal candidate",
    intent: "cycle-inspect",
    workflowFile: "sovereign-eight-hour-cycle.yml",
  },
  {
    id: "workflow-verify",
    label: "Inspect Verify Mahoraga",
    command: "Inspect the last Verify Mahoraga workflow run on GitHub.",
    owner: "repository",
    plane: "github",
    group: "GitHub ledger",
    hint: "Exact-head Ubuntu + Windows gate.",
    keywords: "verify mahoraga workflow ci",
    intent: "workflow-inspect",
    workflowFile: "verify.yml",
  },
  {
    id: "workflow-integration",
    label: "Inspect Autonomous Integration",
    command: "Inspect the last Autonomous Integration workflow run on GitHub.",
    owner: "admin",
    plane: "github",
    group: "GitHub ledger",
    hint: "Squash-merge path after exact-head Verify.",
    keywords: "autonomous integration merge workflow",
    intent: "workflow-inspect",
    workflowFile: "autonomous-integration.yml",
  },
  {
    id: "workflow-destiny",
    label: "Inspect Destiny relay validator",
    command: "Inspect the last Validate Destiny Codex Relay workflow run.",
    owner: "relay",
    plane: "github",
    group: "GitHub ledger",
    hint: "Read-only envelope validation. Not a trigger fire.",
    keywords: "destiny codex relay validate workflow",
    intent: "workflow-inspect",
    workflowFile: "destiny-codex-relay.yml",
  },
  {
    id: "workflow-release",
    label: "Inspect staged release",
    command: "Inspect the last Publish Staged Mahoraga Update workflow run.",
    owner: "admin",
    plane: "github",
    group: "GitHub ledger",
    hint: "Packages a beta. Does not activate Windows.",
    keywords: "release publish staged update beta",
    intent: "workflow-inspect",
    workflowFile: "release.yml",
  },
  {
    id: "workflow-gateway",
    label: "Inspect Cloud Task Gateway",
    command: "Inspect the last Mahoraga Cloud Task Gateway workflow run.",
    owner: "admin",
    plane: "github",
    group: "GitHub ledger",
    hint: "Issue-to-runner gateway.",
    keywords: "cloud task gateway workflow",
    intent: "workflow-inspect",
    workflowFile: "cloud-task-gateway.yml",
  },
  {
    id: "workflow-codex",
    label: "Inspect Codex Cloud dispatch",
    command: "Inspect the last Dispatch Codex Cloud tasks workflow run.",
    owner: "repository",
    plane: "github",
    group: "GitHub ledger",
    hint: "Queued Codex tasks. Licensed-cloud, not this deck.",
    keywords: "codex cloud dispatch workflow",
    intent: "workflow-inspect",
    workflowFile: "codex-cloud-dispatch.yml",
  },
  {
    id: "workflow-chromebook",
    label: "Inspect Chromebook control plane",
    command: "Inspect the last Chromebook control plane workflow run.",
    owner: "relay",
    plane: "github",
    group: "GitHub ledger",
    hint: "Outbound Chromebook lane.",
    keywords: "chromebook control plane workflow",
    intent: "workflow-inspect",
    workflowFile: "chromebook-control-plane.yml",
  },
  {
    id: "workflow-receiver",
    label: "Inspect workspace agent receiver",
    command: "Inspect the last Workspace agent receiver workflow run.",
    owner: "relay",
    plane: "github",
    group: "GitHub ledger",
    hint: "Cloud worker receiver.",
    keywords: "workspace agent receiver workflow",
    intent: "workflow-inspect",
    workflowFile: "workspace-agent-receiver.yml",
  },
  {
    id: "protect-inspect",
    label: "Inspect main protection",
    command: "Inspect the Protect main GitHub ruleset and prove exact-head Verify is enforced.",
    owner: "admin",
    plane: "write",
    group: "GitHub writes",
    hint: "Ruleset 22284961 is active. This is the #78 proof.",
    keywords: "protect main ruleset branch protection 78",
    intent: "github-write",
    writeVerb: "protect-inspect",
    issueNumber: 78,
  },
  {
    id: "merge-97",
    label: "Merge PR #97",
    command: "Merge pull request #97 into main with squash.",
    owner: "admin",
    plane: "write",
    group: "GitHub writes",
    hint: "Blocked until Verify Ubuntu + Windows + Vercel workspace are green.",
    keywords: "merge 97 squash candidate scan report",
    intent: "github-write",
    writeVerb: "merge-pr",
    issueNumber: 97,
  },
  {
    id: "merge-98",
    label: "Merge PR #98",
    command: "Merge pull request #98 into main with squash.",
    owner: "admin",
    plane: "write",
    group: "GitHub writes",
    hint: "Verify currently fails. Will not squash past the ruleset.",
    keywords: "merge 98 squash integration dispatch",
    intent: "github-write",
    writeVerb: "merge-pr",
    issueNumber: 98,
  },
  {
    id: "merge-99",
    label: "Merge PR #99",
    command: "Merge pull request #99 into main with squash.",
    owner: "admin",
    plane: "write",
    group: "GitHub writes",
    hint: "Blocked until exact-head Verify is green. Same as #97.",
    keywords: "merge 99 squash candidate scan report",
    intent: "github-write",
    writeVerb: "merge-pr",
    issueNumber: 99,
  },
  {
    id: "approve-97",
    label: "Approve PR #97",
    command: "Approve pull request #97 from this console.",
    owner: "admin",
    plane: "write",
    group: "GitHub writes",
    hint: "Owner review. Merge still needs exact-head Verify.",
    keywords: "approve 97 review",
    intent: "github-write",
    writeVerb: "approve-pr",
    issueNumber: 97,
  },
  {
    id: "comment-78",
    label: "Comment on #78",
    command: "Comment on #78: Protect main ruleset is active with required Verify checks. Closing from evidence.",
    owner: "admin",
    plane: "write",
    group: "GitHub writes",
    hint: "Posts as the connected GitHub owner.",
    keywords: "comment 78 protect main",
    intent: "github-write",
    writeVerb: "comment",
    issueNumber: 78,
  },
  {
    id: "close-78",
    label: "Close issue #78",
    command: "Close issue #78 as completed.",
    owner: "admin",
    plane: "write",
    group: "GitHub writes",
    hint: "Only after the ruleset proof cell exists.",
    keywords: "close 78 completed",
    intent: "github-write",
    writeVerb: "close-issue",
    issueNumber: 78,
  },
  {
    id: "comment-51",
    label: "Comment on #51",
    command:
      "Comment on #51: Cloud operator deck now owns GitHub writes. Self-update produces a candidate PR; merge still requires exact-head Verify. 3.6.0 remains the Windows rollback.",
    owner: "repair",
    plane: "write",
    group: "GitHub writes",
    hint: "Answers what you can do to update yourself.",
    keywords: "comment 51 self-update",
    intent: "github-write",
    writeVerb: "comment",
    issueNumber: 51,
  },
  {
    id: "cycle-dispatch",
    label: "Dispatch 4hr cycle",
    command: "Dispatch the four-hour sovereign candidate cycle on GitHub.",
    owner: "repair",
    plane: "write",
    group: "GitHub writes",
    hint: "Owner workflow_dispatch. Does not activate Windows.",
    keywords: "dispatch fire cycle workflow_dispatch 4hr",
    intent: "github-write",
    writeVerb: "dispatch-workflow",
    workflowFile: "sovereign-eight-hour-cycle.yml",
  },
  {
    id: "cycle-dispatch-force",
    label: "Force 4hr cycle window",
    command: "Dispatch the four-hour sovereign candidate cycle on GitHub with force=true.",
    owner: "repair",
    plane: "write",
    group: "GitHub writes",
    hint: "Re-runs the current anchored window.",
    keywords: "dispatch force cycle window",
    intent: "github-write",
    writeVerb: "dispatch-workflow",
    workflowFile: "sovereign-eight-hour-cycle.yml",
  },
  {
    id: "delete-preview",
    label: "Preview Wave A deletes",
    command: "Preview Wave A contained-branch deletions listed in issue #83.",
    owner: "admin",
    plane: "write",
    group: "GitHub writes",
    hint: "ahead_by=0, no open PR, not main. Nothing is deleted.",
    keywords: "preview delete wave a branches 83",
    intent: "github-write",
    writeVerb: "delete-preview",
    issueNumber: 83,
  },
  {
    id: "delete-wave-a",
    label: "Delete eligible Wave A branches",
    command: "Delete the eligible Wave A contained branches listed in issue #83.",
    owner: "admin",
    plane: "write",
    group: "GitHub writes",
    hint: "Only branches that pass the ledger. main is untouchable.",
    keywords: "delete wave a contained branches 83",
    intent: "github-write",
    writeVerb: "delete-branch",
    issueNumber: 83,
  },
  {
    id: "create-issue",
    label: "Create a GitHub issue",
    command: "Create a GitHub issue: Operator deck follow-up from the unified console.",
    owner: "admin",
    plane: "write",
    group: "GitHub writes",
    hint: "Opens an issue as the connected owner.",
    keywords: "create issue post github",
    intent: "github-write",
    writeVerb: "create-issue",
  },
  {
    id: "cli-status",
    label: "Local status",
    command: "Run npm run status on the local Mahoraga runtime at 127.0.0.1:4782.",
    owner: "repository",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Windows/Chromebook loopback. This console cannot see it.",
    keywords: "status cli local runtime loopback",
    intent: "loopback-denied",
    cliHint: "npm run status",
  },
  {
    id: "cli-start",
    label: "Start local runtime",
    command: "Start Mahoraga on the local runtime with npm run start against 127.0.0.1:4782.",
    owner: "repair",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Candidate 7.0 must not replace 3.6.0 without the gate.",
    keywords: "start production local runtime",
    intent: "loopback-denied",
    cliHint: "npm run start",
  },
  {
    id: "cli-verify",
    label: "Local npm run verify",
    command: "Run npm run verify on the local Mahoraga runtime.",
    owner: "repository",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Full local gate. Not the GitHub workflow.",
    keywords: "npm run verify local test baseline",
    intent: "loopback-denied",
    cliHint: "npm run verify",
  },
  {
    id: "cli-health",
    label: "Submit system.health",
    command: "Run npm run submit:health on the local Mahoraga runtime.",
    owner: "repair",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Leases a local-core health task.",
    keywords: "submit health system.health",
    intent: "loopback-denied",
    cliHint: "npm run submit:health",
  },
  {
    id: "cli-self-upgrade",
    label: "Validate self-upgrade instruction",
    command: "Run npm run self-upgrade:validate on the local Mahoraga runtime.",
    owner: "repair",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Instruction validator. Activation is verify-then-rollback.",
    keywords: "self-upgrade validate instruction",
    intent: "loopback-denied",
    cliHint: "npm run self-upgrade:validate",
  },
  {
    id: "cli-cycle",
    label: "Local cloud-cycle:candidate",
    command: "Run npm run cloud-cycle:candidate on the local Mahoraga runtime.",
    owner: "repair",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Same worker as GitHub. Needs GH_TOKEN on the host.",
    keywords: "cloud-cycle candidate worker local",
    intent: "loopback-denied",
    cliHint: "npm run cloud-cycle:candidate",
  },
  {
    id: "cli-coordination",
    label: "List coordination assignments",
    command: "Run npm run coordination:list on the local Mahoraga runtime.",
    owner: "coordinator",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Assignment ledger lives on disk, not this deck.",
    keywords: "coordination list assignments",
    intent: "loopback-denied",
    cliHint: "npm run coordination:list",
  },
  {
    id: "cli-coordination-validate",
    label: "Validate coordination ledger",
    command: "Run npm run coordination:validate on the local Mahoraga runtime.",
    owner: "coordinator",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Validates assignment files on disk.",
    keywords: "coordination validate ledger",
    intent: "loopback-denied",
    cliHint: "npm run coordination:validate",
  },
  {
    id: "cli-secondary",
    label: "Secondary runner status",
    command: "Run npm run secondary:status on the local Mahoraga runtime.",
    owner: "relay",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Outbound mailbox runner.",
    keywords: "secondary status mailbox runner",
    intent: "loopback-denied",
    cliHint: "npm run secondary:status",
  },
  {
    id: "cli-workspace-agent",
    label: "Workspace agent health",
    command: "Run npm run workspace-agent:health on the local Mahoraga runtime.",
    owner: "relay",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Cloud worker is declared disabled in the manifest.",
    keywords: "workspace-agent health trigger",
    intent: "loopback-denied",
    cliHint: "npm run workspace-agent:health",
  },
  {
    id: "cli-workspace-status",
    label: "Workspace agent status",
    command: "Run npm run workspace-agent:status on the local Mahoraga runtime.",
    owner: "relay",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Receiver status on disk.",
    keywords: "workspace-agent status",
    intent: "loopback-denied",
    cliHint: "npm run workspace-agent:status",
  },
  {
    id: "cli-destiny-validate",
    label: "Validate Destiny envelope",
    command: "Run npm run destiny:validate on the local Mahoraga runtime.",
    owner: "relay",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Local envelope validator. Does not ACK.",
    keywords: "destiny validate envelope",
    intent: "loopback-denied",
    cliHint: "npm run destiny:validate",
  },
  {
    id: "cli-codex-list",
    label: "List Codex Cloud tasks",
    command: "Run npm run codex-cloud:list on the local Mahoraga runtime.",
    owner: "repository",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Queued licensed-cloud tasks. Listing is local.",
    keywords: "codex cloud list tasks",
    intent: "loopback-denied",
    cliHint: "npm run codex-cloud:list",
  },
  {
    id: "cli-gap-audit",
    label: "Gap audit",
    command: "Run npm run gap:audit on the local Mahoraga runtime.",
    owner: "assurance",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Provider-gap worker on loopback.",
    keywords: "gap audit provider",
    intent: "loopback-denied",
    cliHint: "npm run gap:audit",
  },
  {
    id: "cli-github-audit",
    label: "GitHub audit script",
    command: "Run npm run github:audit on the local Mahoraga runtime.",
    owner: "admin",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Repo audit CLI. This deck already reads public metadata live.",
    keywords: "github audit script cli",
    intent: "loopback-denied",
    cliHint: "npm run github:audit",
  },
  {
    id: "cli-providers",
    label: "Probe providers",
    command: "Run npm run providers:probe on the local Mahoraga runtime.",
    owner: "assurance",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Readiness is evidence, not a flag.",
    keywords: "providers probe readiness",
    intent: "loopback-denied",
    cliHint: "npm run providers:probe",
  },
  {
    id: "cli-baseline",
    label: "Verify release baseline",
    command: "Run npm run baseline:verify on the local Mahoraga runtime.",
    owner: "repair",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Rollback target remains 3.6.0 until the alpha gate passes.",
    keywords: "baseline verify rollback",
    intent: "loopback-denied",
    cliHint: "npm run baseline:verify",
  },
  {
    id: "cli-verify-conversation",
    label: "Verify conversation plane",
    command: "Run npm run verify:conversation-plane on the local Mahoraga runtime.",
    owner: "relay",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Relay + conversation-plane tests on the host.",
    keywords: "verify conversation plane relay",
    intent: "loopback-denied",
    cliHint: "npm run verify:conversation-plane",
  },
  {
    id: "cli-update-manifest",
    label: "Update manifest",
    command: "Run npm run update:manifest on the local Mahoraga runtime.",
    owner: "repository",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Rewrites mahoraga.manifest.json on disk.",
    keywords: "update manifest",
    intent: "loopback-denied",
    cliHint: "npm run update:manifest",
  },
  {
    id: "cli-relay-package",
    label: "Package Destiny relay",
    command: "Run npm run relay:package on the local Mahoraga runtime.",
    owner: "relay",
    plane: "loopback",
    group: "Loopback runtime",
    hint: "Builds the relay package locally. Does not publish a listener.",
    keywords: "relay package destiny",
    intent: "loopback-denied",
    cliHint: "npm run relay:package",
  },
  {
    id: "deny-tunnel",
    label: "Prove inbound tunnel deny",
    command: "Open an ngrok tunnel into my device so Mahoraga can SSH in.",
    owner: "assurance",
    plane: "denied",
    group: "Hard deny",
    hint: "Assurance refuses. Use GitHub events instead.",
    keywords: "ngrok cloudflared reverse ssh tunnel inbound",
    intent: "inbound-tunnel-denied",
  },
  {
    id: "deny-destiny-fire",
    label: "Fire Destiny / Cloud Pro",
    command: "Fire a Destiny Codex dispatch and spend Cloud Pro credits from this deck.",
    owner: "relay",
    plane: "denied",
    group: "Hard deny",
    hint: "receiptTrust unconfigured. Zero-credit deck will not spend.",
    keywords: "destiny fire cloud pro model credits spend",
    intent: "authority-denied",
  },
  {
    id: "deny-destiny-create",
    label: "Create Destiny envelope",
    command: "Run npm run destiny:create and fire a new Destiny Codex envelope from this deck.",
    owner: "relay",
    plane: "denied",
    group: "Hard deny",
    hint: "Create stays on loopback after trust is configured. This deck will not spend.",
    keywords: "destiny create envelope spend",
    intent: "authority-denied",
  },
  {
    id: "deny-activate",
    label: "Activate 7.0 on Windows",
    command: "Activate Mahoraga 7.0.0-alpha.1 on the live Windows production runtime.",
    owner: "repair",
    plane: "denied",
    group: "Hard deny",
    hint: "Docs refuse this. Production rollback remains 3.6.0.",
    keywords: "activate windows 7.0 production replace",
    intent: "authority-denied",
  },
];

export const AGENT_SIGNATURE: Record<AgentId, string> = {
  coordinator: "List the command arsenal and show what this deck can run live versus GitHub, loopback, or deny.",
  scout: "Fetch https://github.com/michaeljwilliams0123/mahoraga and extract the current public summary.",
  admin: "Inspect the Protect main GitHub ruleset and prove exact-head Verify is enforced.",
  assurance: "Audit outbound-only connection posture. Deny inbound tunnels. Report relay and GitHub surfaces.",
  relay: "Inspect the last Validate Destiny Codex Relay workflow run.",
  repository: "Inspect the live Mahoraga repository: health, open issues, and current head.",
  repair: "Inspect the four-hour sovereign candidate cycle, last GitHub run, and whether Mahoraga actually self-updated.",
};

export const ARSENAL_GROUPS: CommandPlane[] = ["live", "write", "github", "loopback", "denied"];

export const PLANE_LABEL: Record<CommandPlane, string> = {
  live: "Live on this deck",
  write: "GitHub writes",
  github: "GitHub ledger",
  loopback: "Loopback runtime",
  denied: "Hard deny",
};

export const PLANE_SHORT: Record<CommandPlane, string> = {
  live: "Live",
  write: "Write",
  github: "Ledger",
  loopback: "Loopback",
  denied: "Deny",
};

export const PLANE_ACTION: Record<CommandPlane, string> = {
  live: "Run",
  write: "Commit",
  github: "Inspect",
  loopback: "Receipt",
  denied: "Prove deny",
};

export const PLANE_COPY: Record<CommandPlane, string> = {
  live: "Runs now. Public GitHub, allowlisted GET, isolation, and denials. Zero tokens.",
  write: "Owner gh session. Merge, comment, close, dispatch, delete eligible branches. Respects Protect main.",
  github: "Reads live Actions metadata. Dispatch is on the write plane.",
  loopback: "Correct plane is 127.0.0.1:4782 on your host. Dispatch prints the exact CLI receipt.",
  denied: "Proven refuses. Inbound tunnels, Destiny spend, Windows 7.0 activate.",
};

export function arsenalStats() {
  const counts = { live: 0, write: 0, github: 0, loopback: 0, denied: 0, total: ARSENAL.length };
  for (const command of ARSENAL) counts[command.plane] += 1;
  return counts;
}

export function commandsForPlane(plane: CommandPlane): ArsenalCommand[] {
  return ARSENAL.filter((command) => command.plane === plane);
}

export function commandsForAgent(owner: AgentId): ArsenalCommand[] {
  return ARSENAL.filter((command) => command.owner === owner);
}

export function searchArsenal(query: string): ArsenalCommand[] {
  const q = query.trim().toLowerCase();
  if (!q) return ARSENAL;
  const parts = q.split(/\s+/).filter(Boolean);
  return ARSENAL.filter((command) => {
    const hay =
      `${command.id} ${command.label} ${command.keywords} ${command.command} ${command.owner} ${command.cliHint ?? ""} ${command.workflowFile ?? ""} ${command.issueNumber ?? ""} ${command.writeVerb ?? ""}`.toLowerCase();
    return parts.every((part) => hay.includes(part));
  });
}

export function matchArsenalCommand(text: string): ArsenalCommand | null {
  const lower = text.trim().toLowerCase();
  if (!lower) return null;
  const exact =
    ARSENAL.find((command) => command.command.toLowerCase() === lower) ??
    ARSENAL.find((command) => command.label.toLowerCase() === lower) ??
    ARSENAL.find((command) => command.id === lower) ??
    ARSENAL.find((command) => command.cliHint && command.cliHint.toLowerCase() === lower);
  if (exact) return exact;
  const hits = searchArsenal(text);
  return hits.length === 1 ? hits[0] : null;
}

export function coverageLine(snapshot: GithubSnapshot | null): string {
  const stats = arsenalStats();
  const liveNote = snapshot?.ok ? `${snapshot.openIssues} issues · ${snapshot.openPrs} pulls` : "GitHub waiting";
  const writeNote = snapshot?.write?.ok ? `write ${snapshot.write.login}` : "write waiting";
  return `${stats.live} live · ${stats.write} write · ${stats.github} GitHub · ${stats.loopback} loopback · ${stats.denied} deny · ${writeNote} · ${liveNote}`;
}
