/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=deploy/cloudflare-execution-runtime/wrangler.jsonc --include-runtime=false deploy/cloudflare-execution-runtime/worker-configuration.d.ts` (hash: f4f0fedda191b4b5cb6dca7e2d5f2365)
interface __BaseEnv_Env {
	EXECUTION_DO: DurableObjectNamespace<import("./worker").ExecutionDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "ExecutionDurableObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
