/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=deploy/cloudflare-execution-runtime/wrangler.jsonc --include-runtime=false deploy/cloudflare-execution-runtime/worker-configuration.d.ts` (hash: 89d4af67caa03887e0a135507a89db3b)
interface __BaseEnv_Env {
	TARGET_SHA: "7cb8aab1129875f798347afdb2844f963e986a65";
	RAILWAY_ANCHOR_URL: "https://mahoraga-runtime-main-production.up.railway.app/";
	EXECUTION_DO: DurableObjectNamespace<import("./worker").ExecutionDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "ExecutionDurableObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TARGET_SHA" | "RAILWAY_ANCHOR_URL">> {}
}
